version: "3.9"

services:
  db:
    image: postgres:16
    container_name: billing_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billing
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: billing_backend
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/billing
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: billing_frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  pgdata:
